---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=242738"
changelog_format: json

# Regex for Version
version: "{{ register_changelog.json['latest_version'] }}"

# Download URL
url: "https://wwcom.ch/downloads/cti_{{ version | regex_replace('[.]', '_') }}.exe"
url64: "https://wwcom.ch/downloads/cti64_{{ version | regex_replace('[.]', '_') }}.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*url\s*=\s*)('.*')
      replace: "$url = '{{ url }}'"
    - regwxp: (^\s*[$]*checksum\s*=\s*)('.*')
      replace: "$checksum = '{{ file_hash }}'"

    - regwxp: (^\s*[$]*url64\s*=\s*)('.*')
      replace: "$url64 = '{{ url64 }}'"
    - regwxp: (^\s*[$]*checksum64\s*=\s*)('.*')
      replace: "$checksum64 = '{{ file64_hash }}'"

# readme to description
readme:
  start: 4
  end: 36

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.wwphone-cti.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
