---
# chocomilk vars

# Package Changelog
changelog: "https://raw.githubusercontent.com/open-circle-ltd/chocolatey.version/master/wwphone.cti.json"

# Regex for Version
version: "{{ register_changelog.content |
  regex_search('\\d+.\\d+.\\d+\\b')
  }}"

# Download URL
url: "https://wwcom.ch/downloads/cti_{{ version | regex_replace('.', '_') }}.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 6
  end: 18

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: chocolatey
    repository: "https://nuget.itigo.tech/upload"
    key: "{{ lookup('env','CHOCOLATEY_ITIGO_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.wwphone.cti.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"