---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=242738"

# Regex for Version
version: "{{ register_changelog.json['latest_version'] }}"

# Download URL
url: "https://wwcom.ch/downloads/cti_{{ version | regex_replace('[.]', '_') }}.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*urlPackage\s*=\s*)('.*')
      replace: "$urlPackage = '{{ url }}'"
    - regwxp: (^\s*[$]*checksumPackage\s*=\s*)('.*')
      replace: "$checksumPackage = '{{ file_hash }}'"

# readme to description
readme:
  start: 4
  end: 30

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.wwphone-cti.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
